# Generated by Django 3.0.6 on 2020-05-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_auto_20200529_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=20000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='abc.png', upload_to='bookreview')),
            ],
        ),
        migrations.AlterField(
            model_name='artical',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
