# Generated by Django 3.0.6 on 2020-05-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_bibidh_blog_interview_islamic_itihash_law_personality_politics_recentworld_somajsongsker_songbad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itihash',
            name='slug',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='itihash',
            name='title',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='songbad',
            name='slug',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='songbad',
            name='title',
            field=models.CharField(max_length=1500),
        ),
    ]
