# Generated by Django 3.0.6 on 2020-06-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_brakingnews_electedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brakingnews',
            name='image',
            field=models.ImageField(default='abc.png', upload_to='BrakingNews'),
        ),
        migrations.AlterField(
            model_name='electedpost',
            name='image',
            field=models.ImageField(default='abc.png', upload_to='ElectedPost'),
        ),
    ]
