# Generated by Django 3.0.6 on 2020-06-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_auto_20200611_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bibidh',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='brakingnews',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electedpost',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interview',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='islamic',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itihash',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='law',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personality',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='politics',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recentworld',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='somajsongsker',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='songbad',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
